export const CONTACT_REQUEST = 'CONTACT_REQUEST';
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS';
export const CONTACT_FAILURE = 'CONTACT_FAILURE';
export const SET_CONTACT = "SET_CONTACT"

export const GET_IN_TOUCH_REQUEST = 'GET_IN_TOUCH_REQUEST';
export const GET_IN_TOUCH_SUCCESS = 'GET_IN_TOUCH_SUCCESS';
export const GET_IN_TOUCH_FAILURE = 'GET_IN_TOUCH_FAILURE';
export const SET_GET_IN_TOUCH = "SET_GET_IN_TOUCH"

export const FETCH_REQUEST = "FETCH_REQUEST"
export const FETCH_SUCCESS = "FETCH_SUCCESS"
export const FETCH_FAILURE = "FETCH_FAILURE"
export const SET_FETCH = "SET_FETCH"

export const LIKE_REQUEST = "LIKE_REQUEST"
export const LIKE_SUCCESS = "LIKE_SUCCESS"
export const LIKE_FAILURE = "LIKE_FAILURE"
export const SET_LIKE = "SET_LIKE"